### ISSUE TITLE
フロントエンドのセットアップ

### ISSUE THREAD

**Issue by a27yb** [Caffeins/gap#2]
フロントエンドのセットアップ、何したら良いか分かりません。

参考資料：https://qiita.com/Kobayashi2019/items/66c03b29d8f5effd2341

やった事：backned, frontendの二つのディレクトリを作成し、docker関連のファイルをいじりました。そもそもフロントエンドで何のアプリを使うのかわからない＋npm, yarnってなに？状態なので、助けてください。

やってほしい事：dockerにおけるfrontendの設定を終了させて、**docker-compose up** で全てのコンテナが正常に立ち上がる状態にしてほしいです。

**Comment by a27yb** [comment]
お願いし申しましもうします

**Comment by Takuya-Yamamot** [comment]
@umepon0626 @a27yb 
Frontendですが、next.jsの使用はどうでしょうか？
普通のReactでもいいですがルーティングとか楽になります。
そのままでもOKです！
